// @ts-check
// 初始使用 autogenerated 侧边栏；按需改写为手工定义。

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
